### PR TITLE
Major fixes.

### PR DESCRIPTION
**Pull request by GamePlayer-8**
Heyo,

Basically I was experimenting a bit with it.
And I have:
 - [x] fixed clock blinking;
 - [x] packed add app into one exe (for linux only atm).

Still AppImage is in WIP due to the issues with https://github.com/orgs/pyinstaller/discussions/7551 .

### CODE REVIEW

**Comment by GamePlayer-8** [comment]
In order to compile manually please use `podman run --rm -it $(pwd):/source alpine sh /source/init.sh` inside a working dir.

**Comment by GamePlayer-8** [comment]
⚠️ Atm due to AppImage problems, compiled exe would work only with `musl`.

**Comment by GamePlayer-8** [comment]
Pylint fixes will income soon..

**Comment by Rexxt** [comment]
i guess i can merge this with a couple edits, give me a minute

**Pull request merged**
